import React from 'react';
import { Link } from 'react-router-dom';
import { 
  ArrowRight, Brain, Target, Calendar, MessageSquare, 
  BookOpen, CheckCircle, Zap, Shield
} from 'lucide-react';

const FeatureCard = ({ icon: Icon, title, description, color }) => (
  <div className="glass-card p-8 rounded-3xl border border-border hover:border-primary/50 transition-all duration-300 group">
    <div className={`w-14 h-14 rounded-2xl ${color} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
      <Icon className="text-white" size={28} />
    </div>
    <h3 className="text-xl font-bold mb-3">{title}</h3>
    <p className="text-foreground/60 leading-relaxed">{description}</p>
  </div>
);

const Landing = () => {
  return (
    <div className="min-h-screen bg-background overflow-hidden relative">
      {/* Background Orbs */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-primary/20 rounded-full blur-[120px] -z-10 animate-pulse" />
      <div className="absolute bottom-[10%] right-[-10%] w-[40%] h-[40%] bg-blue-500/10 rounded-full blur-[100px] -z-10" />

      {/* Navbar */}
      <nav className="max-w-7xl mx-auto px-6 py-8 flex items-center justify-between relative z-10">
        <div className="flex items-center gap-2">
          <div className="w-10 h-10 bg-primary rounded-xl flex items-center justify-center shadow-lg shadow-primary/30">
            <Brain className="text-white" size={24} />
          </div>
          <span className="text-2xl font-bold tracking-tight">EduTrack AI</span>
        </div>
        <div className="hidden md:flex items-center gap-8 text-sm font-medium">
          <a href="#features" className="text-foreground/60 hover:text-primary transition-colors">Features</a>
          <a href="#about" className="text-foreground/60 hover:text-primary transition-colors">About</a>
          <a href="#contact" className="text-foreground/60 hover:text-primary transition-colors">Support</a>
        </div>
        <div className="flex items-center gap-4">
          <Link to="/login" className="px-6 py-2.5 text-sm font-semibold hover:text-primary transition-colors">Sign In</Link>
          <Link to="/signup" className="px-6 py-2.5 bg-primary text-white text-sm font-semibold rounded-full shadow-lg shadow-primary/25 hover:scale-105 active:scale-95 transition-all">Get Started</Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-6 pt-20 pb-32 relative z-10 text-center">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-8 animate-bounce">
          <Zap size={16} className="text-primary fill-primary" />
          <span className="text-xs font-bold text-primary uppercase tracking-widest">Next-Gen Education Platform</span>
        </div>
        <h1 className="text-6xl md:text-8xl font-black mb-8 leading-[1.1] tracking-tight">
          Master Your Academics <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-indigo-500 to-blue-500">
            Powered by AI.
          </span>
        </h1>
        <p className="text-xl text-foreground/60 max-w-2xl mx-auto mb-12 leading-relaxed">
          Predict your performance, identify weaknesses, and get personalized 
          study plans generated by state-of-the-art machine learning models.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-6">
          <Link to="/signup" className="group px-10 py-5 bg-primary text-white font-bold rounded-2xl shadow-2xl shadow-primary/30 flex items-center gap-3 hover:scale-105 hover:bg-primary/90 transition-all text-lg">
            Start Your Journey <ArrowRight size={20} className="group-hover:translate-x-1 transition-transform" />
          </Link>
          <button className="px-10 py-5 bg-white/5 dark:bg-white/5 backdrop-blur-md border border-border font-bold rounded-2xl hover:bg-white/10 transition-all text-lg flex items-center gap-2">
            View Live Demo
          </button>
        </div>

        {/* Floating Dashboard Preview */}
        <div className="mt-24 relative max-w-5xl mx-auto group">
          <div className="absolute -inset-1 bg-gradient-to-r from-primary to-blue-500 rounded-[2.5rem] blur opacity-25 group-hover:opacity-40 transition duration-1000 group-hover:duration-200"></div>
          <div className="relative glass-card rounded-[2rem] border border-white/20 overflow-hidden shadow-2xl">
            <img 
              src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=2070" 
              alt="Dashboard Preview" 
              className="w-full h-auto opacity-90"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent"></div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section id="features" className="max-w-7xl mx-auto px-6 py-32 border-t border-border/50">
        <div className="text-center mb-16">
          <h2 className="text-4xl font-bold mb-4">Powerful Features</h2>
          <p className="text-foreground/60 max-w-xl mx-auto">Everything you need to excel in your studies, all in one intelligent platform.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <FeatureCard 
            icon={Target} 
            title="Performance Prediction" 
            description="Our ML models analyze your scores and attendance to predict your final exam results with 95% accuracy."
            color="bg-orange-500"
          />
          <FeatureCard 
            icon={Shield} 
            title="Weakness Detection" 
            description="AIGI-powered analysis identifies exactly which topics need your attention before they become problems."
            color="bg-primary"
          />
          <FeatureCard 
            icon={Calendar} 
            title="Smart Schedules" 
            description="Dynamic study timetables that automatically adjust based on your progress and upcoming deadlines."
            color="bg-green-500"
          />
          <FeatureCard 
            icon={MessageSquare} 
            title="AI Tutor 24/7" 
            description="Have a doubt? Our AI chatbot is trained on academic datasets to provide instant, clear explanations."
            color="bg-blue-500"
          />
          <FeatureCard 
            icon={BookOpen} 
            title="Notes Generator" 
            description="Convert complex topics into concise, high-yield revision notes with formulas and key takeaways."
            color="bg-purple-500"
          />
          <FeatureCard 
            icon={CheckCircle} 
            title="Progress Tracking" 
            description="Visualize your improvement over time with beautiful, interactive charts and achievement badges."
            color="bg-pink-500"
          />
        </div>
      </section>

      {/* Footer */}
      <footer className="max-w-7xl mx-auto px-6 py-20 border-t border-border/50 flex flex-col md:flex-row justify-between items-center gap-8">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-primary rounded-lg flex items-center justify-center">
            <Brain className="text-white" size={18} />
          </div>
          <span className="text-xl font-bold tracking-tight">EduTrack AI</span>
        </div>
        <p className="text-foreground/40 text-sm">© 2026 EduTrack AI. Pioneering Intelligent Education.</p>
        <div className="flex gap-6 text-foreground/60 text-sm">
          <a href="#" className="hover:text-primary transition-colors">Privacy</a>
          <a href="#" className="hover:text-primary transition-colors">Terms</a>
          <a href="#" className="hover:text-primary transition-colors">Twitter</a>
        </div>
      </footer>
    </div>
  );
};

export default Landing;
